tasks:
  - name: Install Requirements
    init: pip install -r requirements.txt
  - name: Install Playwright Dependences
    init: playwright install-deps
  - name: Install Playwright
    init: playwright install